# Generated by Django 4.2.6 on 2023-10-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('number', models.IntegerField(max_length=30)),
                ('image', models.ImageField(default='uploads/images/profile.jpg', upload_to='uploads/images')),
            ],
        ),
    ]
